{"name": "Ошибка при проверке пользователя с некорректным паролем", "status": "passed", "start": 1718881389902, "stop": 1718881390854, "uuid": "27b8cc53-5566-4853-a29a-d54e617c0d8f", "historyId": "f7a9e6fe3d698a8f58d67b8da6fa3c37", "testCaseId": "f7a9e6fe3d698a8f58d67b8da6fa3c37", "fullName": "tests.test_login_user.TestLoginUser#test_login_incorrect_password_failed_result", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "LAPTOP-8BB0DG15"}, {"name": "thread", "value": "19632-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}